language: python
services: mongodb
python:
  - '3.6'
install:
  - python setup.py develop
  - pip install -r requirements-dev.txt
script:
  - py.test -vv
  - cd static/js/tests; npm install; npm test
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    on_success: never
